/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class StyleConstants {
  static readonly ZERO_POINT_FIVE = 0.5;
  static readonly EIGHTY_PERCENT = '80%';
  static readonly FULL = '100%';
  static readonly TRUE = true;
  static readonly FALSE = false;
  static readonly WIDTH_16 = 16;
  static readonly WIDTH_20 = 20;
  static readonly WIDTH_40 = 40;
  static readonly WIDTH_90 = 90;
  static readonly WIDTH_320 = 320;
  static readonly HEIGHT_40 = 40;
  static readonly HEIGHT_56 = 56;
  static readonly HEIGHT_60 = 60;
  static readonly LAYOUT_WEIGHT = 1;
  static readonly MARGIN_LEFT_6 = 6;
  static readonly MARGIN_LEFT_10 = 10;
  static readonly MARGIN_LEFT_12 = 12;
  static readonly MARGIN_LEFT_MINUS_12 = -12;
  static readonly MARGIN_RIGHT_7 = 7.66;
  static readonly MARGIN_RIGHT_8 = 8;
  static readonly MARGIN_RIGHT_12 = 12;
  static readonly MARGIN_TOP_12 = 12;
  static readonly MARGIN_TOP_16 = 16;
  static readonly MARGIN_TOP_280 = 280;
  static readonly MARGIN_BOTTOM_12 = 12;
  static readonly PADDING_LEFT_14 = 14;
  static readonly PADDING_LEFT_16 = 16;
  static readonly PADDING_RIGHT_14 = 14;
  static readonly PADDING_RIGHT_16 = 16;
  static readonly PADDING_TOP_10 = 10;
  static readonly PADDING_BOTTOM_10 = 10;
  static readonly BORDER_RADIUS_12 = 12;
  static readonly BORDER_RADIUS_16 = 16;
  static readonly FONT_SIZE_12 = 12;
  static readonly FONT_SIZE_17 = 17;
  static readonly FONT_SIZE_18 = 18;
  static readonly FONT_SIZE_20 = 20;
  static readonly LINE_HEIGHT_18 = 18;
  static readonly LINE_HEIGHT_20 = 20;
  static readonly LINE_HEIGHT_27 = 27;
  static readonly FONT_WEIGHT_400 = 400;
  static readonly FONT_WEIGHT_700 = 700;
}