/*
 *
 *    Copyright (c) 2025 Huawei Device Co., Ltd.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 *
 */

export class PageConstants {
  static readonly IMAGE_ASPECT_RATIO: number = 1;

  static readonly  MAIN_PAGE_URL: string = 'pages/MainPage';

  static readonly HOME_INDEX: number = 0;

  static readonly SCAN_INDEX: number = 1;

  static readonly PERSONAL_INDEX: number = 2;

  static readonly  LOGIN_PAGE_URL: string = 'pages/LoginPage';


}