import { SignupInfo } from '../activity/SignUpPage';

export const signupList: SignupInfo[] = [
  { id: '001', name: '张三', sex: '男', age: 25, activity: '端午民俗嘉年华', activityId: 1 },
  { id: '002', name: '李娜', sex: '女', age: 30, activity: '夜游灯会大赏', activityId: 2 },
  { id: '003', name: '王刚', sex: '男', age: 22, activity: '湖畔音乐露营', activityId: 3 },
  { id: '004', name: '赵丽', sex: '女', age: 28, activity: '城市马拉松', activityId: 4 },
  { id: '005', name: '陈东', sex: '男', age: 35, activity: '夏日水上乐园', activityId: 5 },
  { id: '006', name: '刘燕', sex: '女', age: 19, activity: '非遗文化节', activityId: 6 },
  { id: '007', name: '孙敏', sex: '女', age: 41, activity: '新开园：梦幻花海', activityId: 7 },
  { id: '008', name: '周杰', sex: '男', age: 29, activity: 'VR 探险体验馆', activityId: 8 },
  { id: '009', name: '吴磊', sex: '男', age: 26, activity: '科技艺术展', activityId: 9 },
  { id: '010', name: '郑爽', sex: '女', age: 33, activity: '创意市集', activityId: 10 },
  { id: '011', name: '钱文', sex: '男', age: 45, activity: '秘境徒步挑战', activityId: 11 },
  { id: '012', name: '马丽', sex: '女', age: 27, activity: '古镇文化体验', activityId: 12 },
  { id: '013', name: '邓超', sex: '男', age: 38, activity: '自然野趣观察', activityId: 13 },
  { id: '014', name: '杨幂', sex: '女', age: 31, activity: '星空摄影之夜', activityId: 14 },
  { id: '015', name: '朱亚', sex: '男', age: 24, activity: '摄影比赛', activityId: 15 },
  { id: '016', name: '高圆', sex: '女', age: 36, activity: '汉服巡游', activityId: 16 },
  { id: '017', name: '林更新', sex: '男', age: 32, activity: '美食节', activityId: 17 },
  { id: '018', name: '迪丽', sex: '女', age: 23, activity: '宠物嘉年华', activityId: 18 }
];