/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export class StyleConstant {
  /**
   * Permissions.
   */
  static readonly FOUR_HUNDRED: number = 400;
  static readonly TWENTY: number=20;
  static readonly FIVE_HUNDRED: number=500;
  static readonly DIVIDER_WIDTH: number=2;
  static readonly SEVEN_HUNDRED: number=700;
  static readonly SIX_HUNDRED:  number = 600;
  static readonly EIGHT_HUNDRED:  number = 800;
  static readonly ROTATE_ANGLE: string | number=-50;
  static readonly SPACE_TWO: number = 2;
  static readonly SEVEN_BORDER_RADIUS: Length = 7;
  static readonly ZERO: number = 0;
  static readonly THREE: number=3;
  static readonly TEXT_MAX_LINES: number=1;
}