/**
 * 地图相关常量
 */
export class MapConstants {
  /* 尺寸比例 */
  public static readonly FULL_SIZE = '100%';
  public static readonly COMMUTING_WIDTH = '99%';
  public static readonly TITLE_WIDTH = '90%';
  public static readonly MAPCOMPONENT_HEIGHT = '85%';
  public static readonly FULL_HEIGHT = '200%';
  public static readonly LIST_HEIGHT_FOLD = '20%';
  public static readonly LIST_HEIGHT_EXPAND = '40%';
  
  /* space */
  public static readonly PUBLIC_SPACE = 12;
  public static readonly PUBLIC_SPACE_MD = 8;
  public static readonly PUBLIC_SPACE_TABBAR = 21;
  
  // 地图高度
  public static readonly MAP_HEIGHT = 134;
  
  // 定位图标
  public static readonly IC_LOCATION_SIZE = 32;
  public static readonly IC_ARROW_SIZE = 14;
  public static readonly IC_COMMUTING_ARROW_SIZE = 10;
  
  // 地图组件标题高度
  public static readonly TITLE_HEIGHT = 48;
  
  // 后退键图标
  public static readonly IC_BACK_WIDTH = 24;
  public static readonly IC_BACK_HEIGHT = 16;
  
  // 列表导航栏
  public static readonly LIST_BAR_WIDTH = 48;
  public static readonly LIST_BAR_HEIGHT = 4;
  
  // 背景模糊
  public static readonly BACK_BLUR = 10;
  
  /* 内边距 */
  public static readonly PADDING_MAP_TOP = 25;
  public static readonly PADDING_LARGE = 16;
  public static readonly PADDING = 12;
  public static readonly PADDING_BUTTON = 10;
  public static readonly PADDING_LABEL_VERTICAL = 1;
  public static readonly PADDING_LABEL_HORIZONTAL = 8;
  
  // 边框半径
  public static readonly BORDER_RADIUS_LARGE = 32;
  public static readonly BORDER_RADIUS = 16;
  public static readonly BORDER_RADIUS_BAR = 2;
  
  // 字体
  public static readonly FONT_SIZE_LARGER = 24;
  public static readonly FONT_SIZE_LARGE = 18;
  public static readonly FONT_SIZE_MD = 14;
  public static readonly FONT_SIZE_SMALL = 12;
  public static readonly FONT_SIZE_SMALLER = 10;
  public static readonly FONT_WEIGHT_TITLE = 600;
  public static readonly FONT_WEIGHT = 500;
  public static readonly FONT_LINEHEIGHT = 16;
  public static readonly FONT_LABEL_LINEHEIGHT = 13;
  
  // 动画时间
  public static readonly EXPANDING_DURATION = 300;
  public static readonly MOVECAMERA_DURATION = 500;
  
  // 搜寻范围（米）
  public static readonly DISTANCE = 2000;
}

